name: Send email with attachment and commit file
on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
 send-email:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v2.3.4
     
     - name: Send Email with Attachment
       uses: dawidd6/action-send-mail@v3.7.1
       with:
           server_address: smtp.gmail.com
           server_port: 465 
           username: ${{ secrets.MAIL_USERNAME }}
           password: ${{ secrets.MAIL_PASSWORD }}
           subject: "Email with Attachment and Commit File"
           Body: "Please find the commit message and attachment attached below"
           To: mounikakallepalli@vcollab.com
           from: Kallepallimounika333@gmail.com
           content_type: text/html/zip/Image
           attachments: |
             D:\a\TestApp_new\TestApp_new\Image\Capture.PNG
          
        
      
          
        
          
     
