
name: Releases
on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
       
    env:
       Solution_Path: Testapp.sln
       depency: depency\VCollabDependencyAPI
       PYTHONPATH_64_38: depency\VCollabDependencyAPI\Python38_64bit
    steps: 
      - uses: actions/checkout@v2.3.4
      
      - uses: suisei-cn/actions-download-file@v1.0.1
        name: Download the file from url
        with:
           url: "https://downloads.vcollab.com/tmp/VCollabDependencyapi.7z" 
           target: depency
           
      - name: Extract zip file 
        uses: DuckSoft/extract-7z-action@v1.0
        with:
           pathsource: depency\VCollabDependencyAPI.7z 
           pathtarget: depency
      
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
          
      - name: Build app for release 
        run: |
          msbuild Testapp.sln /p:Configuration=Release /p:Platform=x64 > Testapp_log.txt -m
          
          
      - name: copy exe file
        run: copy D:\a\TestApp_new\TestApp_new\Testapp_log.txt D:\a\TestApp_new\TestApp_new\logs
        
      - name: upload files to ftp.
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
         server: ${{ secrets.FTP_SERVER }}
         username: ${{ secrets.FTP_USERNAME }}
         password: ${{ secrets.FTP_PASSWORD }}
         protocol: ftps
         port : 2133
         local-dir: ./log/       
         server-dir: ./test/ 
         
      - name: Send email notification on success
        uses: dawidd6/action-send-mail@v3.7.1
        with:
          server_address: smtp.gmail.com
          server_port: 465 
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject:  job status Notification
          Body: |
            Testapp build was success and files uploaded to ftp server.
          To: mounikakallepalli@vcollab.com
          from: Kallepallimounika333@gmail.com
          content_type: text/html
         
      - name: Send email notification on failure
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3.7.1
        with:
          server_address: smtp.gmail.com
          server_port: 465 
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject:  job status Notification
          Body: |
            Testapp build was failure
          To: mounikakallepalli@vcollab.com
          from: Kallepallimounika333@gmail.com
          content_type: text/html
         
    
         
             

