name: Copy Testapp.exe to Another Repository

on:
  push:
     branches: ["master"]

jobs:
  copy_exe_file:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2.3.4
        with:
          repository: Mounik05/TestApp_new
          ref: master

      - name: Copy Testapp.exe
        run: |
          mkdir New-repo 
          copy 'D:\a\TestApp_new\TestApp_new\x64\Release\Testapp.exe' New-repo 

      - name: Commit and Push Changes
        run: |
          cd New-repo 
          git init
          git config --local user.email "Kallepallimounika333@gmail.com"
          git config --local user.name "Mounik05"
          git add .
          git commit -m "Copy Testapp.exe from source repository"
          git remote add origin https://github.com/Mounik05/New-repo.git
          git push -u origin master
