name: Copy Testapp.exe to Another Repository

on:
  push:
     branches: ["master"]

jobs:
  copy_exe_file:
    runs-on: windows-latest
    
    steps: 
      - uses: actions/checkout@v2.3.4
      
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: Mounik05/TestApp_new # Replace with the source repository URL
          ref: master

      - name: Create Destination Directory
        run: |
          mkdir 'D:\a\New-repo\New-repo'
          
      - name: Copy .exe files
        run: |
          Copy-Item 'D:\a\TestApp_new\TestApp_new\x64\Release\TestApp.exe'  'D:\a\New-repo\New-repo'
          
      - name: Commit and push changes.
        run: |
            cd "D:\a\New-repo\New-repo"
            git init
            git config --local user.name "Mounik05"
            git remote add origin https://github.com/Mounik05/New-repo.git
            git add .
            git commit -m "Copy .exe files from source repository"
            git push -u origin master
