name: Releases
on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
       
    steps: 
      - uses: actions/checkout@v2.3.4
      
      - name: Detect and Backup Deleted Files
        id: detect-deleted
        run: |
          # Create a temporary directory to store deleted files
          mkdir deleted_files

          # Check for deleted files between current and previous commit
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | while read -r file; do
            if [ -f "$file" ]; then
              echo "Backing up deleted file: $file"
              cp "$file" deleted_files/
            fi
          done

      - name: Upload Deleted Files Artifact
        uses: actions/upload-artifact@v2
        with:
          name: deleted-files
          path: deleted_files
          
          
