name: Commit After File Push

on:
  push:
      branches: ["master"]

jobs:
  conditional_job_check_files:
    runs-on: windows-latest
    outputs:
      exe_changed: ${{ steps.check_file_changed.outputs.exe_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check file changes
        shell: pwsh
        id: check_file_changed
        run: |
          $diff = git diff --name-only HEAD^ HEAD
          $HasDiff = $diff -contains 'TestApp.exe'
          Write-Host "::set-output name=exe_changed::$HasDiff"

  conditional_job:
    runs-on: windows-latest
    needs: [conditional_job_check_files]
    if: needs.conditional_job_check_files.outputs.exe_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Commit files
        run: |
          git config --local user.email "kallepallimounika333@gmail.com"
          git config --local user.name "Mounik05"
          git lfs install
          git lfs track "*TestApp.exe"
          git add .gitattributes
          git add .
          git commit -m "Commit TestApp.exe changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          
          
