name: Copy Testapp.exe to Another Repository

on:
  push:
     branches: ["master"]

jobs:
  copy_exe_file:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2.3.4
        with:
          repository: Mounik05/TestApp_new
          ref: master

      - name: Checkout Destination Repository
        uses: actions/checkout@v2.3.4
        with:
          repository:  Mounik05/New-repo
          token: ${{ secrets.GITHUB_TOKEN }}
          path: New-repo

      - name: Copy Testapp.exe
        run: |
          robocopy 'TestApp_new/<source-directory>' 'New-repo/<destination-directory>' 'Testapp.exe'

      - name: Commit and Push Changes
        run: |
          cd 'New-repo'
          git config --local user.email "Kallepallimounika333@gmail.com"
          git config --local user.name "Mounik05"
          git add .
          git commit -m "Copy executable file from source repository"
          git push
