name: Deploy for preview

on:
  push:
    paths:
      - mailtest/test2.txt
    
jobs:
  upload:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Check if File Modified
        id: check_file
        run: |
          filePath="mailtest/test2.txt"
          fileModified=false
          if [ -f "$filePath" ]; then
            lastModified=$(git log -1 --format=%at -- "$filePath")
            currentModified=$(git log -1 --format=%at)
            if [ "$lastModified" == "$currentModified" ]; then
              fileModified=false
            else
              fileModified=true
            fi
           fi
          echo "::set-output name=fileModified::$fileModified"

      - name: Your job step
        if: ${{ needs.check_file.outputs.fileModified == 'true' }}
        run: |
          # Perform the necessary actions for your job
