name: Commit and Push Workflow

on:
   push:
    branches: ["master"]

jobs:
  commit_and_push:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Commit file
        run: |
          git config --local user.name "Mounik05"
          git config --local user.email "Mounik05@github.com"
          git add D:\a\TestApp_new\TestApp_new\file1.txt
          git commit -m "Automatically commit file1.txt after push"
          git push
      
