name: Copy Testapp.exe to Another Repository

on:
  push:
     branches: ["master"]

jobs:
  copy_exe_file:
    runs-on: windows-latest
    
    steps: 
      - uses: actions/checkout@v2.3.4
      
      - name: Checkout source repository
        uses: actions/checkout@v2.3.4
        with:
          repository: Mounik05/TestApp_new # Replace with the source repository URL
          ref: master
          
      - name: Create destination directory
        run: mkdir 'D:\a\New-repo\New-repo'

      - name: Copy TestApp.exe
        run: cp 'D:\a\TestApp_new\TestApp_new\x64\Release\TestApp.exe' 'D:\a\New-repo\New-repo'
          
      - name: Change directory
        run: |
          cd 'D:\a\New-repo\New-repo'
          git config --local user.name "Mounik05"
          git config --local user.email "kallepallimounika333@gmail.com"
          git add -A
          git commit -m "copied"
          git push https://github.com/Mounik05/New-repo.git
          git status
        env:
          REPO_KEY: ${{secrets.GH_PAT}}
