name:  File Check Workflow
on:
  push:
      branches: ["master"]

jobs:
  conditional_job_check_files:
    runs-on: 'windows-latest'
    # Declare outputs for next jobs
    outputs:
      docs_changed: ${{ steps.check_file_changed.outputs.docs_changed }}
    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
     
  conditional_job:
    runs-on: windows-latest
    needs: [conditional_job_check_files]
    if: needs.conditional_job_check_files.outputs.docs_changed == 'True'
    steps:
    - uses: actions/checkout@v2
    
   
