name: Commit and Push Workflow

on:
   push:
    branches: ["master"]

jobs:
  commit_and_push:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Commit file
        run: |
          git config user.name "Your Name"
          git config user.email "your-email@example.com"
          git add new.txt
          git commit -m "Automatically commit new.txt file after push
          git push
