name: upload artifact
on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
 send-email:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v2.3.4
     
     - name: Upload Artifact
       uses: actions/upload-artifact@v2
       with:
         name: my-artifact
         path: D:\a\TestApp_new\TestApp_new\mailtest\test.txt
