name: Commit and Push Workflow

on:
   push:
    branches: ["master"]

jobs:
  commit_and_push:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Commit file to target repository
        run: |
           git config user.name "Mounik05"
           git config user.email "kallepallimounika333@gmail.com"
           git add path/to/your/file.txt
           git commit -m "Automatically commit file.txt after push"
           git push
