name: Releases
on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
       
    steps: 
      - uses: actions/checkout@v2.3.4
      
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
          
      - name: Build app for release 
        run: |
          msbuild Testapp.sln /p:Configuration=Release /p:Platform=x64 > Testapp_log.txt -m
          
      - name: send email notifiation
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3.7.1
        with:
           server_address: smtp.gmail.com
           server_port: 465 
           username: ${{ secrets.MAIL_USERNAME }}
           password: ${{ secrets.MAIL_PASSWORD }}
           subject: "job failure notification"
           Body: "Testapp build was failed"
           To: mounikakallepalli@vcollab.com
           from: Kallepallimounika333@gmail.com
           content_type: text/html
           attachments: |
                D:\a\TestApp_new\TestApp_new\Testapp_log.txt
                     
                     
