name: Commit and Push Workflow

on:
   push:
    branches: ["master"]

jobs:
  commit_and_push:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Commit file to target repository
        run: |
          git clone https://github.com/Mounik05/VCollabprozip.git
          cd VCollabprozip
          git config user.name "Mounik05"
          git config user.email "kallepallimounika333@gmail.com"
          git checkout master
          cp D:\a\TestApp_new\TestApp_new\file1.txt
          git add file1.txt
          git commit -m "Automatically commit file1.txt after push from source repository"
          git push origin main
