name: Releases
on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps: 
       - uses: actions/checkout@v2.3.4
      
       - name: setup-msbuild
         uses: microsoft/setup-msbuild@v1.1
         with:
          msbuild-architecture: x64
          
       - name: Build app for release
         run: msbuild TestApp.sln -t:rebuild /p:Platform=x64 /p:Configuration=Release /p:LocalizedBuild=true
        
       - name: Push changes
         run: |
             git config --local user.email "kallepallimounika333@gmail.com"
             git config --local user.name "kallepalli34"
             git add .
             git commit -m "Add changes" -a
             git push -u origin master
