name:  File Check Workflow
on:
  push:
      branches: ["master"]

jobs:
  conditional_job_check_files:
    runs-on: 'windows-latest'
    # Declare outputs for next jobs
    outputs:
      docs_changed: ${{ steps.check_file_changed.outputs.docs_changed }}
    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: pwsh
      id: check_file_changed
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD

        # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
        $SourceDiff = $diff | Where-Object { $ -match '^docs/' -or $ -match '.md$' }
        $HasDiff = $SourceDiff.Length -gt 0

        # Set the output named "docs_changed"
        Write-Host "::set-output name=docs_changed::$HasDiff"

  # Run the job only with "docs_changed" equals "True"
  conditional_job:
    runs-on: 'windows-latest'
    needs: [ conditional_job_check_files ]
    if: needs.conditional_job_check_files.outputs.docs_changed == 'True'
    steps:
    #- shell: pwsh
    - uses: actions/checkout@v2
      
    - name: Build the installer
      run: | 
           cd NSIS
           makensis.exe Testapp.nsi
       
    - name: Commit files
      run: |
          git config --local user.email "kallepallimounika333@gmail.com"
          git config --local user.name "Mounik05"
          git lfs install
          git lfs track "*Testapp.exe"
          git add .gitattributes
          git add .
          git commit -m "Add changes" -a
       
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{secrets.GH_PAT}} 
          
