name: Copy Testapp.exe to Another Repository

on:
  push:
     branches: ["master"]

jobs:
  copy_exe_file:
    runs-on: windows-latest
    
    steps: 
      - uses: actions/checkout@v2.3.4
       
      #- name: Create destination directory
      #  run: mkdir 'D:\a\New-repo\New-repo'

      #- name: Change directory.
      #  run: |
      #   cp 'D:\a\TestApp_new\TestApp_new\x64\Release\TestApp.exe' 'D:\a\New-repo\New-repo'
      #   cd 'D:\a\New-repo\New-repo'
      #    git config --local user.name "Mounik05"
      #    git config --local user.email "kallepallimounika333@gmail.com"
      #    git add -A
      #    git commit -m "copied"
      #    git push https://github.com/Mounik05/New-repo.git
      #  env:
      #    REPO_KEY: ${{secrets.GH_PAT}}
      
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
         repository: Mounik05/VCollabprozip
         path: pro
         token: ${{secrets.GH_PAT}}
         
      - name: Copy files from repo to another repo
        run: |
          cp file1.txt pro\file.txt
          cd pro
          git config --local user.name "Mounik05"
          git config --local user.email "Mounik05@github.com"
          git add -A
          git commit -m "copied"
          git push
