name: Copy Testapp.exe to Another Repository

on:
  push:
     branches: ["master"]

jobs:
  copy_exe_file:
    runs-on: windows-latest
    
    steps: 
      - uses: actions/checkout@v2.3.4
      
      - name: Checkout to release
        uses: actions/checkout@v2.3.4
        with:
         repository: Mounik05/New-repo
         path: New-repo
         token: ${{secrets.GH_PAT}}
         
      - name: Copy files from repo to another repo.
        run: |
          cp 'D:\a\TestApp_new\TestApp_new\x64\Release\TestApp.exe' New-repo\TestApp.exe
          cd New-repo
          git config --local user.name "Mounik05"
          git config --local user.email "kallepallimounika333@gmail.com"
          git add -A
          git commit -m "copied"
          git push https://github.com/Mounik05/New-repo.git
        env:
          REPO_KEY: ${{secrets.GH_PAT}}
