name: Releases
on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
       
    steps: 
      - uses: actions/checkout@v2.3.4
      
      - name: Check if file exists
        run: |
          if [ -f "Resource.txt" ]; then
            echo "File exists"
          else
            echo "File does not exist"
          fi

      - name: Backup file
        if: "! fileExists('Resource.txt')"
        run: |
          cp Resource.txt ./backups/Resource.txt
          
          
          
          
