name: File Check Workflow
on:
  push:
   branches: ["master"]
jobs:
  conditional_job_check_files:
    runs-on: 'windows-latest'
    # Declare outputs for next jobs
    outputs: 
      docs_changed: ${{ steps.check_file_changed.outputs.docs_changed }}
    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
     
    - name: Check if file exists.
      id: check_file_changed
      run: |
        # Check if a specific file exists
        if (Test-Path "D:\a\TestApp_new\TestApp_new\mailtest\test.txt") {
        Write-Host "::set-output name=docs_changed::True"
        } else {
         Write-Host "::set-output name=docs_changed::False"
         }
         
   
  conditional_job:
    runs-on: windows-latest
    needs: [conditional_job_check_files]
    if: needs.conditional_job_check_files.outputs.docs_changed == 'True'
    steps:
    - uses: actions/checkout@v2
    
    - name: Commit Changes and push changes
      run: |
          git config --local user.email "kallepallimounika333@gmail.com"
          git config --local user.name "Mounik05"
          git add D:\a\TestApp_new\TestApp_new\mailtest\test.txt
          git commit -m "Updated file"
          git push
