name: Commit After File Push

on:
  push:
      branches: ["master"]

jobs:
  conditional_job_check_files:
    runs-on: 'windows-latest'
    # Declare outputs for next jobs
    outputs:
      exe_changed: $_{{ steps.check_file_changed.outputs.exe_changed }}
    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: pwsh
      id: check_file_changed
      run: |
        # Diff HEAD with the previous commit
        $_diff = git diff --name-only HEAD^ HEAD

        # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
        $_SourceDiff = $_diff | Where-Object {$_ -match '^docs/' -or $_ -match '.md$_' }
        $_HasDiff = $_SourceDiff.Length -gt 0

        # Set the output named "exe_changed"
        Write-Host "::set-output name=exe_changed::$_HasDiff"
          
  conditional_job:
    runs-on: windows-latest
    needs: [conditional_job_check_files]
    if: needs.conditional_job_check_files.outputs.exe_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Commit files
        run: |
          git config --local user.email "kallepallimounika333@gmail.com"
          git config --local user.name "Mounik05"
          git lfs install
          git lfs track "*TestApp.exe"
          git add .gitattributes
          git add .
          git commit -m "Commit TestApp.exe changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          
          
