name: Copy Testapp.exe to Another Repository

on:
  push:
     branches: ["master"]

jobs:
 commit:
      runs-on: windows-latest
    
      steps: 
      - uses: actions/checkout@v2.3.4
  
      - name: Configure Git
        run: |
            git config user.name "Mounik05"
            git config user.email "kallepallimounika333@gmail.com"

      - name: Commit changes
        run: |
          git add D:\a\TestApp_new\TestApp_new\file1.txt
          git commit -m "Committing changes to D:\a\TestApp_new\TestApp_new\file1.txt"
          git push
