name: Deploy for preview

on:
  push:
    paths:
      - mailtest/test2.txt

jobs:
  upload:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Your job step
        if: github.event_name == 'push' && (github.event.head_commit.modified | contains('mailtest/test2.txt') || !github.event.head_commit.modified)
        run: |
