name: Send email
on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
 send-email:
   runs-on: windows-latest
   steps:
     - name: Send Email to Single Recipient.
       uses: dawidd6/action-send-mail@v3.7.1
       with:
          server_address: smtp.gmail.com
          server_port: 465 
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          from: Kallepallimounika333@gmail.com
          To: aravinthkumar@vcollab.com
          subject: github action result
          body: Build job of ${{github.repository}} completed successfully!
          html_body: file://TestApp_new
          

          
        
          
     
