name: Releases
on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
       
    steps: 
      - uses: actions/checkout@v2.3.4
      
      - name: Set up Git
        run: |
          git config --global user.name "Mounik05"
          git config --global user.email "kallepallimounika333@gmail.com"

      
      - name: Create backup branch
        run: |
          git checkout -b backup-branch
          git add .
          git commit -m "Backup deleted file: ${{ github.event.ref }}"

      - name: Push backup branch
        uses: ad-m/github-push-action@v1
        with:
          branch: backup-branch
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          
          
          
          
