name: Commit After File Push
on:
  push:
    branches: ["master"]

jobs:
  commit:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Set up Git
        run: |
          git config user.name "Mounik05"
          git config user.email "kallepallimounika333@gmail.com"

      - name: Commit changes
        run: |
         cd D:\a\TestApp_new\TestApp_new\file1.txt
         git add new.txt
         git commit -m "file1.txt changed to new.txt"
         
      - name: Push changes
        run: |
         cd D:\a\TestApp_new\TestApp_new\new.txt
         git push
    
    
    
    
