name: Deploy for preview
on:
  push:
    paths:
      - mailtest/test2.txt
    
jobs:
  upload:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Modify File
        id: modify-file
        run: |
          echo "New content" > mailtest/test.txt

      - name: Check if File Pushed
        run: |
          echo "Checking if file was pushed..."

      - name: Perform Action
        needs: [upload, modify-file]
        run: |
          echo "File was modified and pushed. Performing the action..."
