name: Commit After File Push

on:
  push:
      branches: ["master"]

jobs:
  commit:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "Mounik05"
          git config --global user.email "kallepallimounika333@gmail.com"

      - name: Check if file is modified
        id: check_file
        run: |
          git diff --name-only origin/main..HEAD | findstr /C:"D:\a\TestApp_new\TestApp_new\file1.txt"

      - name: Commit Changes
        if: steps.check_file.outputs.return-code == '0'
        run: |
          git add D:\a\TestApp_new\TestApp_new\file1.txt
          git commit -m "Updated file"
          git push
          
          
          
