name: Commit After File Push
on:
  push:
    branches: ["master"]
    paths:
      - D:\a\TestApp_new\TestApp_new\file1.txt

jobs:
  commit:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Configure Git
        run: |
          git config user.name "Mounik05"
          git config user.email "kallepallimounika333@gmail.com"

      - name: Commit changes
        run: |
          git add example.txt
          git commit -m "Committing changes to file1.txt"
          git push
