name: Deploy for preview
on:
  push:
   paths:
        - mailtest/test2.txt
jobs:
  modify_file_job:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if File Exists
        run: |
          if test -f D:a\TestApp_new\TestApp_new\mailtest\test2.txt; then
            echo "File exists"
          else
            echo "File does not exist, skipping the job"
            exit 0
          fi

      - name: Check File Modification
        id: check-modification
        run: |
          if git diff --quiet --D:a\TestApp_new\TestApp_new\mailtest\test2.txt; then
            echo "File has not been modified, skipping the job"
            exit 0
          fi

      - name: Modify File
        run: |
          echo "Perform file modification here"
          echo "123" >> D:a\TestApp_new\TestApp_new\mailtest\test2.txt

      - name: Commit Changes
        run: |
          git config --local user.email "kallepallimounika333@gmail.com"
          git config --local user.name "Mounik05"
          git commit -am "Update file" --quiet

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
