name: Commit File Workflow

on:
  push:
      branches: ["master"]
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
         repository: Mounik05/VCollabprozip
         path: 'D:\a\TestApp_new\TestApp_new\file1.txt'
         token: ${{secrets.GH_PAT}}
      
      - name: Configure Git
        run: |
          git config --global user.name "Mounik05"
          git config --global user.email "kallepallimounika333@gmail.com"

      - name: Commit Changes
        run: |
          git add D:\a\TestApp_new\TestApp_new\file1.txt
          git commit -m "Updated file"
          git push
           
 
          
          
          
