name: Deploy for preview

on:
  push:
    paths:
      - mailtest/test2.txt

jobs:
  precheck:
    runs-on: windows-latest

    steps:
      - name: Check if File Exists
        id: check_file
        run: |
          cmd /c "
          file_path=D:a\TestApp_new\TestApp_new\mailtest\test.txt
          if not exist "$file_path" (
            echo File not found, job should not start
            exit /b 1
          )

          for /F %A in ('git log -1 --format=%ct -- "%file_path%"') do set last_modified=%A
          for /F %B in ('git log -1 --format=%ct') do set current_modified=%B
          if %last_modified% equ %current_modified% (
            echo File exists but not modified, job should not start
            exit /b 1
          )
          "

  upload:
    needs: precheck
    runs-on: windows-latest

    steps:
      - name: Your job step
        run: |
      # Perform the necessary actions for your job
