name: Releases
on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
       
    steps: 
      - uses: actions/checkout@v2.3.4
      
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
          
      - name: Build app for release 
        run: |
          msbuild Testapp.sln /p:Configuration=Release /p:Platform=x64 > output.txt -m
           
      - name: email notifiation
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3.7.1
        with:
           on_success: never
           on_failure: always
           username: ${{ secrets.MAIL_USERNAME }}
           subject: The job has failed
           Body: " echo The job has failed. Please check the build logs for more details"
           content_type: "text/html"
