name: Job with File Check

on:
  push:
    paths:
      - mailtest/test2.txt

jobs:
  your_job_name:
    runs-on: windows-latest
    if: exists('mailtest/test2.txt')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if File Exists
        run: |
          if [ ! -f "test2.txt" ]; then
            echo "File not found, job should not start"
            exit 1
          fi

      - name: Your job step
        if: steps.check_file.outcome != 'failure'
        run: |
        
        
        
