name: Send email
on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
 send-email:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v2.3.4
     - name: Send Email to Single person
       uses: dawidd6/action-send-mail@v3.7.1
       with:
          server_address: smtp.gmail.com
          server_port: 465 
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Example email with attachment
          To: kallepallimounika123@yahoo.com
          from: Kallepallimounika333@gmail.com
          body: Please find the attached document
          content_type: text/html
          attachments: D:\a\TestApp_new\TestApp_new\mailtest\test.txt
     - name:  commit test.txt file
       run: echo "${{ github.event.head_commit.message}}" > uploadnewfile.txt
     - name: Commit message file
       run: |
          git config --global user.email "mounikakallepalli333@gmail.com"
          git config --global user.name "Mounik05"
          git add D:\a\TestApp_new\TestApp_new\mailtest\test.txt
          git commit -m "uploadnewfile.txt" 
        
            
          
         
          
        
      
          
        
          
     
