name: Copy Testapp.exe to Another Repository

on:
  push:
     branches: ["master"]

jobs:
  copy_exe_file:
    runs-on: windows-latest
    
    steps: 
      - uses: actions/checkout@v2.3.4
      
      - name: Checkout Source Repository
        uses: actions/checkout@v2
        with:
          repository: Mounik05/TestApp_new
          ref: master

      - name: Create Destination Directory
        run: |
          mkdir 'D:\a\New-repo\New-repo'

      - name: Copy Testapp.exe
        run: |
          copy 'D:\a\TestApp_new\TestApp_new\x64\Release\Testapp.exe' 'D:\a\New-repo\New-repo\Testapp.exe'
          
      - name: Change Directory to Destination
        run: |
          cd 'D:\a\New-repo\New-repo'
          git init
          git config --local user.email "Kallepallimounika333@gmail.com"
          git config --local user.name "Mounik05"
          git remote add origin https://github.com/Mounik05/New-repo.git
          git add .
          git commit -m "Copy Testapp.exe from source repository"
          git push -u origin master
