name: Deploy for preview
on:
  push:
    paths:
     - mailtest/test.txt
    
jobs:
  upload:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2.3.4
      
      - name: Modify File
        run: |
          echo "123" > mailtest/test.txt

      - name: Check if File Pushed
        run: |
          echo "push Process success." 
          
      - name: Commit Changes and push changes
        run: |
          git config --local user.email "kallepallimounika333@gmail.com"
          git config --local user.name "Mounik05"
          git add D:\a\TestApp_new\TestApp_new\mailtest\test.txt
          git commit -m "Updated file"
          git push
