name: Send email with attachment and commit file
on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
 send-email:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v2.3.4
     
     - name: Create commit message file
       run: |
         echo "${{ github.event.head_commit.message }}" > sample.txt
         
     - name: Commit message file
       run: |
          git config --global user.email "mounikakallepalli333@gmail.com"
          git config --global user.name "Mounik05"
          git add .
          git add sample.txt
          git commit -m "Add and attach sample.txt"
          git tag -a "v1.0" -m "Add and attach sample.txt"
          git push --follow-tags
          
     - name: Attach and commit file
       uses: dawidd6/action-send-mail@v3.7.1
       with:
           server_address: smtp.gmail.com
           server_port: 465 
           username: ${{ secrets.MAIL_USERNAME }}
           password: ${{ secrets.MAIL_PASSWORD }}
           subject: "Commit message and attachment"
           Body: "Please find the commit message and attachment attached below"
           To: mounikakallepalli@vcollab.com
           from: Kallepallimounika333@gmail.com
           content_type: text/html
           attachments: |
            sample.txt
            .git/refs/tags/v1.0
         
          
        
      
          
        
          
     
