
name: Releases
on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
       
    env:
       Solution_Path: Testapp.sln
       depency: depency\VCollabDependencyAPI
       PYTHONPATH_64_38: depency\VCollabDependencyAPI\Python38_64bit
    steps: 
      - uses: actions/checkout@v2.3.4
      
      - uses: suisei-cn/actions-download-file@v1.0.1
        name: Download the file from url
        with:
           url: "https://downloads.vcollab.com/tmp/VCollabDependencyAPI.7z" 
           target: depency
           
      - name: Extract zip file 
        uses: DuckSoft/extract-7z-action@v1.0
        with:
           pathsource: depency\VCollabDependencyAPI.7z 
           pathtarget: depency
      
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
          
      - name: Build app for release 
        run: |
          msbuild Testapp.sln /p:Configuration=Release /p:Platform=x64 > Testapp_log.txt -m
          
          
      - name: copy exe file
        run: copy D:\a\TestApp_new\TestApp_new\Testapp_log.txt D:\a\TestApp_new\TestApp_new\logs
        
      - name: upload files to ftp.
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
         server: ${{ secrets.FTP_SERVER }}
         username: ${{ secrets.FTP_USERNAME }}
         password: ${{ secrets.FTP_PASSWORD }}
         protocol: ftps
         port : 2133
         local-dir: ./logs/       
         server-dir: ./test/ 
         
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: TestApp.exe

          body: |
            # Release Notes
            This is the first release of my project.
            ## Features
            - first change
            - second change
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./Testapp.zip
          asset_name: Testapp.zip
          asset_content_type: application/zip
      
    
         
             
             
             
          
