name: Copy Testapp.exe to Another Repository

on:
  push:
     branches: ["master"]

jobs:
 commit:
      runs-on: windows-latest
    
      steps: 
      - uses: actions/checkout@v2.3.4
      
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
         repository: Mounik05/VCollabprozip
         path: pro
         token: ${{secrets.GH_PAT}}
         
         
      - name: Copy files from repo to another repo and commit changes.
        run: |
          cp x64\Release\TestApp.exe pro\TestApp.exe
          cd pro
          git config --local user.name "Mounik05"
          git config --local user.email "kallepallimounika333@gmail.com"
          git add D:\a\TestApp_new\TestApp_new\x64\Release\TestApp.exe
          git commit -m "Adding new file D:\a\TestApp_new\TestApp_new\x64\Release\TestApp.exe"
          git push
