name: Deploy for preview
on:
  push:
    paths:
     - mailtest/test.txt
    

jobs:
  modify-file:
    runs-on: windows-latest
    steps:
      - name: Modify File
        run: |
          echo "123" > mailtest/test.txt
          git config --global user.name "Mounik05"
          git config --global user.email "kallepallimounika333@gmail.com"
          git add mailtest/test.txt
          git commit -m "Modify mailtest/test.txt"
          git push

  upload:
    needs: modify-file
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Check if File Pushed
        run: |
          echo "push Process success."
