name: Send email
on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
 send-email:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v2.3.4
     - name: commit file
       run: |
         git log --pretty=format:"%h - %an, %ar : %s" > file.txt 
         
     - uses: dawidd6/action-send-mail@v3.7.1
     - name: Send Email to Single person
       run: |
           TO :'mounikakallepalli@vcollab.com'
           smtpServer = 'smtp.example.com'
           smtpPort = 25
           smtpUsername = 'sender@example.com'
           smtpPassword = 'password'
           emailFrom = 'sender@example.com'
           attachmentPath = 'commit_message.txt'
           attachmentName = 'commit_message.txt'
           mailMessage = New-Object System.Net.Mail.MailMessage
           mailMessage.From = $emailFrom
           mailMessage.To.Add($toEmail)
           mailMessage.Subject = "This is the email subject"
           mailMessage.Body = "Please see attached file for commit message."
           attachment = New-Object System.Net.Mail.Attachment($attachmentPath)
           attachment.Name:$attachmentName
           mailMessage.Attachments.Add($attachment)
           smtpClient = New-Object System.Net.Mail.SmtpClient($smtpServer, $smtpPort)
           smtpClient.EnableSsl = $true
           smtpClient.Credentials = $smtpCredentials
           smtpClient.Send($mailMessage)
                  

        
        
          
         
          
        
      
          
        
          
     
