name: Deploy for preview
on:
  push:
    paths:
      - mailtest/test.txt
    
jobs:
 precheck:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Check if File Pushed.
        run: |
          echo "push Process success."  
          
 upload:
  needs: precheck
  runs-on: windows-latest

  steps:
    - name:  job step
      if: github.event_name == 'push' && (contains(github.event.head_commit.modified, 'mailtest/test2.txt') || !github.event.head_commit.modified)
      run: |
        
        
        
