name: Commit and Push Workflow

on:
   push:
    branches: ["master"]

jobs:
  commit_and_push:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
         repository: Mounik05/VCollabprozip
         #path: pro
         token: ${{secrets.GH_PAT}}
         
      - name: Copy files from repo to another repo.
        run: |
          cp  x64\Release\TestApp.exe pro\TestApp.exe
          cd  pro
          git config --local user.name "Mounik05"
          git config --local user.email "Mounik05@github.com"
          git add TestApp.exe
          git commit -m "Automatically commit TestApp.exe file after push"
          git push
      
