name: Deploy for preview
on:
  push:
   paths:
        - mailtest/test2.txt
        
jobs:
  upload:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2.3.4
      
      - name: Modify file if exists or modified
        run: |
          if test -f   mailtest/test2.txt|| git diff --quiet -- mailtest/test2.txt ; then
            echo "File exists or has been modified, proceeding with further steps"
            echo "123" >> mailtest/test2.txt
          else
            echo "File does not exist or hasn't been modified, skipping the job"
            exit 0
          fi
