name: Send email with attachment and commit file
on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
 send-email:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v2.3.4
     
     - name: Create commit message file
       run: |
        echo "${{ github.event.head_commit.message }}" > newfile.txt
     - name: Commit message file
       run: |
          git config --global user.email "mounikakallepalli333@gmail.com"
          git config --global user.name "Mounik05"
          git add .
          git commit -m "add newfile.txt"
            
     - name: Send Email with Attachment and Commit File
       uses: dawidd6/action-send-mail@v3.7.1
       with:
           server_address: smtp.gmail.com
           server_port: 465 
           username: ${{ secrets.MAIL_USERNAME }}
           password: ${{ secrets.MAIL_PASSWORD }}
           subject: "Email with Attachment and Commit File"
           Body: "Please find the commit message and attachment attached below"
           To: mounikakallepalli@vcollab.com
           from: Kallepallimounika333@gmail.com
           cc: aravindanand07.r@gmail.com
           content_type: text/html
           attachments: |
             D:\a\TestApp_new\TestApp_new\mailtest\test.txt
             D:\a\TestApp_new\TestApp_new\newfile.txt
        
      
          
        
          
     
