name: Add commit message and send email
on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
 send-email:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v2.3.4
     - name: Create commit message file
       run: |
         echo "${{ github.event.head_commit.message }}" > commit-message.txt
     - name: Commit message file
       run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add commit-message.txt
          git commit -m "Add commit message file"
         
     - uses: dawidd6/action-send-mail@v3.7.1
     - name: Send Email to Single person
       with:
           server_address: smtp.gmail.com
           server_port: 465 
           username: ${{ secrets.MAIL_USERNAME }}
           password: ${{ secrets.MAIL_PASSWORD }}
           subject: "New commit on main branch"
           To: kallepallimounika123@yahoo.com
           from: Kallepallimounika333@gmail.com
           attachments: commit-message.txt
           body: |
           
           
        
          
         
          
        
      
          
        
          
     
