name: Check and Modify File
on:
  push:
    paths:
      - D:\a\TestApp_new\TestApp_new\mailtest\test2.txt

jobs:
 update:
    runs-on: windows-latest
    steps:
      - name: Check if File Exists
        run: |
          if [ ! -f "D:\a\TestApp_new\TestApp_new\mailtest\test2.txt" ]; then
            echo "File not found, job should not start"
            exit 1
          fi

      - name: Check if File Modified
        run: |
          # Add your script or command to check file modification
          if [ <file_not_modified_condition> ]; then
            echo "File not modified, job should not start"
            exit 1
          fi

      - name: Your job step
        if: ${{ success() }}
        run: |
