name: Deploy for preview
on:
  push:
    paths:
     # Modify the file directly
      echo "123" > mailtest/test.txt
      - mailtest/test.txt
    
jobs:
  upload:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2.3.4
      
      - name: Check if File Pushed
        run: |
          echo "push Process success." 
