name: Release
on:
  push:
    branches: ["master"]
jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      
      - name: Upload testapp.exe
        uses: actions/upload-artifact@v2
        with:
          name: TestApp.exe
          path:  D:\a\TestApp_new\TestApp_new\x64\Release\Testapp.exe
      
      - name: Download artifact 
        uses: actions/download-artifact@v3
        with:
         name: TestApp.exe
         path:  D:\a\TestApp_new\TestApp_new\mailtest
         
      - name: Push changes
        run: |
             git config --local user.email "kallepallimounika333@gmail.com"
             git config --local user.name "Mounik05"
             git add .
             git commit -m "Add changes" -a
             git push -u origin master
      
      
          
     
