name: Commit File Workflow

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Configure Git
        run: |
          git config --global user.name "Mounik05"
          git config --global user.email "kallepallimounika333@gmail.com"

      - name: Set up Git in Windows environment
        shell: powershell
        run: |
          $env:GIT_TERMINAL_PROMPT = "0"
          $env:GIT_SSH_COMMAND = "-o StrictHostKeyChecking=no"

      - name: Commit and Push Changes
        shell: powershell
        run: |
          git add D:\a\TestApp_new\TestApp_new\file1.txt
          git commit -m "Updated file"
          git push
          
      - name: Push changes
        run: |
             git config --local user.email "kallepallimounika333@gmail.com"
             git config --local user.name "kallepalli34"
             git add .
             git commit -m "Add changes" -a
             git push -u origin master
                  
          
          
          
