name: Release
on:
  push:
    branches: ["master"]
jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: TestApp_new

          body: |
            # Release Notes

            This is the first release of my project.

            ## Features

            - first change
            - second change

          draft: false
          prerelease: false
          
      
          
     
