name: Send commit message and attachment in email
on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
 send-email:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v2.3.4
     
     - name: Create commit message file
       run: echo "${{ github.event.head_commit.message }}" > test.txt

     - name: Commit message file
       run: |
          git config --global user.email "mounikakallepalli333@gmail.com"
          git config --global user.name "Mounik05"
          git add .
          git commit -m "uploadnewfile.txt" 
     
     - name: Send Email to Single person
       uses: dawidd6/action-send-mail@v3.7.1
       with:
           server_address: smtp.gmail.com
           server_port: 465 
           username: ${{ secrets.MAIL_USERNAME }}
           password: ${{ secrets.MAIL_PASSWORD }}
           subject: "Test email with attachment and commit message"
           Body: "Please find the attachment and commit message below"
           To: mounikakallepalli@vcollab.com
           from: Kallepallimounika333@gmail.com
           content_type: text/html
           attachement: D:\a\TestApp_new\TestApp_new\mailtest\test.txt
           run: |
           attachments: |
            uploadnewfile.txt
            
          
     
          
    
          
         
          
        
      
          
        
          
     
