name: Send email
on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
 send-email:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v2.3.4
     
     - name: Send Email to Single Recipient.
       uses: dawidd6/action-send-mail@v3.7.1
       with:
          server_address: smtp.gmail.com
          server_port: 465 
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          from: Kallepallimounika333@gmail.com
          To: aravindanand07.r@gmail.com
          subject: Example email with attachment
          body: Please find the attached document
          content_type: text/html
          attachments: D:\a\TestApp_new\TestApp_new\mailtest\test.txt
         

        
        
          
         
          
        
      
          
        
          
     
