name: Check and Modify File
on:
  push:
   paths:
        - mailtest/test2.txt
jobs:
  modify_file_job:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if File Exists
        run: |
          if not exist D:a\TestApp_new\TestApp_new\mailtest\test2.txt (
            echo "File does not exist, skipping the job"
            exit 0
          )

      - name: Check File Modification
        id: check-modification
        run: |
          echo ::set-output name=modified::$(git log -1 --format="%cd" -- D:a\TestApp_new\TestApp_new\mailtest\test2.txt)

      - name: Modify File
        if: steps.check-modification.outputs.modified != '2023-05-30'
        run: |
          echo "Perform file modification here"
          echo "123" >> D:a\TestApp_new\TestApp_new\mailtest\test2.txt

      - name: Commit Changes
        run: |
          git config --local user.email "kallepallimounika333@gmail.com"
          git config --local user.name "Mounik05"
          git commit -am "Update file" --quiet

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
