name: Releases
on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
       
    env:
       Solution_Path: TestApp.sln
       VCDEP: depency\VCollabDependencyAPI
       PYTHONPATH_64_38: depency\VCollabDependencyAPI\Python38_64bit
    steps: 
      - uses: actions/checkout@v2.3.4
      
      - name: Download the file from url
        uses: suisei-cn/actions-download-file@v1.0.1
        with:
           url: "https://downloads.vcollab.com/tmp/VCollabDependencyAPI.7z" 
           target: depency
           
      - name: Extract zip file 
        uses: DuckSoft/extract-7z-action@v1.0
        with:
           pathsource: depency\VCollabDependencyAPI.7z 
           pathtarget: depency

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
          
      - name: Build app for release 
        run: msbuild TestApp.sln -t:rebuild /p:Platform=x64 /p:Configuration=Release /p:LocalizedBuild=true
     
      - name: Download log archive
        uses: suisei-cn/actions-download-file@v1.0.1
        with:
           url: "https://github.com/Mounik05/TestApp_new/suites/14440387898/logs?attempt=1" 
           target: logs
           
      - name: Upload logs to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
         server: ${{ secrets.FTP_SERVER }}
         username: ${{ secrets.FTP_USERNAME }}
         password: ${{ secrets.FTP_PASSWORD }}
         protocol: ftps
         port : 2133
         local-dir: ./logs/logs_467.zip/       
         server-dir: ./test/
           
     
       
           
      
