name: Job with File Check

on:
  push:
    paths:
      - mailtest/test2.txt

jobs:
 upload:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if File Exists
        run: |
          if [ -e "D:\a\TestApp_new\TestApp_new\mailtest\test2.txt" ]; then
            echo "File found, proceeding with the job"
          else
            echo "File not found, job should not start"
            exit 1
          fi
          shell: bash

      - name: Your job step
        run: |





        
        
