name: Send email with attachment and commit file
on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
 send-email:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v2.3.4
     
     - name: Create commit message file
       run: |
        git log --pretty=format:"%h - %an, %ar : %s" > Testapp.txt
        From: Kallepallimounika333@gmail.com
        Date: Tue may 2 19:41:29 2023 +0530
        Subject: Build_Automation_Test
        
     - name: Commit message file
       run: |
          git config --global user.email "mounikakallepalli333@gmail.com"
          git config --global user.name "Mounik05"
          git add .
          git commit -m "add Testapp.txt"
            
     - name: Send Email with Attachment
       uses: dawidd6/action-send-mail@v3.7.1
       with:
           server_address: smtp.gmail.com
           server_port: 465 
           username: ${{ secrets.MAIL_USERNAME }}
           password: ${{ secrets.MAIL_PASSWORD }}
           subject: "Email with Attachment and Commit File"
           Body: "Please find the commit message and attachment attached below"
           To: mounikakallepalli@vcollab.com
           from: Kallepallimounika333@gmail.com
           content_type: text/html/zip/Image
           attachments: |
             D:\a\TestApp_new\TestApp_new\TestApp\TestApp.aps
             D:\a\TestApp_new\TestApp_new\Testapp.txt
        
      
          
        
          
     
