name: Copy Exe File

on:
  push:
     branches: ["master"]
jobs:
  copy_exe:
    runs-on: windows-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2.3.4
        with:
          repository: Mounik05/TestApp_new
          ref: master

      - name: Download Exe file
        run: |
          Invoke-WebRequest -Uri https://github.com/Mounik05/TestApp_new/releases/download/v1.0/Testapp.exe.zip -OutFile Testapp.exe.zip
          Expand-Archive Testapp.exe.zip - DestinationPath D:\a\new\new
          
      - name: Copy Exe file to destination repository
        run: |
          $sourceDir = "TestApp_new"
          $destinationDir = "$(System.DefaultWorkingDirectory)/new/Testapp_new"
          New-Item -ItemType Directory -Path $destinationDir -Force
          Copy-Item -Path "$sourceDir/Testapp.exe" -Destination "$destinationDir/Testapp.exe" -Force

      - name: Commit and push changes to destination repository
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Mounik05
          author_email: kallepallimounika333@gmail.com
          message: Add Testapp.exe file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
